### ISSUE TITLE
what's the license of this repository?

### ISSUE THREAD

**Issue by anatawa12** [momo-the-monster/package-list-action#11]

**Comment by momo-the-monster** [comment]
Added [VRChat Distro License](https://github.com/vrchat-community/package-list-action/blob/main/License.md), thanks for filing this issue.

**Comment by anatawa12** [comment]
Umm.... Why is this not a open source? I do not want to limit my contributions usages to VRChat Platform.

**Comment by Spokeek** [comment]
@anatawa12 is the license limiting the use of the code to the use of the vrchat plateform only ?
I was reading that this applied to any content that is "made available through the VRChat Platform", Section 4.1 of the SDK Licence.

I may be confused about that.

**Comment by anatawa12** [comment]
I forgot about CLA and CLA says I don't have to limit my contribution for VRChat platform. Sorry

>  it does not change your rights to use your own Contributions for any other purpose.
