### ISSUE TITLE
[BUG] "Latest Package" for webpage deployment does not respect semantic versioning order

### ISSUE THREAD

**Issue by techanon** [momo-the-monster/package-list-action#18]
I have a repo listing with a large amount of pre-release versions. When I check my listing for the latest version of one of my repos that has more than 1 digit in a version numbering, it shows the wrong version.

Example: 
- Go to vpm.techanon.dev 
- Click on the (i) for ProTV 
- Latest should be v3.0.0-alpha.18 (or later)
- Currently shows v3.0.0-alpha.9.1 (and it's associated dependency versions that are also out of date)

This is incorrect. After looking through the repo a bit I believe this line is the issue
https://github.com/vrchat-community/package-list-action/blob/main/PackageBuilder/Build.cs#L237
as it seems to only sort for the "latest package" via descending unicode sort instead of via semantic version syntax.

I would expect it to order the packages according to the same sorting algorithm that the actual JSON listing itself gets sorted by.

**Comment by LauraRozier** [comment]
For now you can use my little edit, until they reviewed and accepted or made their own version.
You can use mine by editing the `/.githubworkflows/build-listing.yml` file of your package-listing page.

Here is my commit to my own that shows the minor change you'll have to make:
https://github.com/LauraRozier/LauraVRCUtils/commit/7446425e7933e6494dbfa6fc107e45ca6769153e

**Comment by Spokeek** [comment]
That looks interesting to have, maybe make a PR to this repo as well so vrc can integrate it at some point.

**Comment by orels1** [comment]
This should be addressed by https://github.com/vrchat-community/package-list-action/pull/31
Thanks @JLChnToZ !
